### PR TITLE
add some basic component tests

### PR DESCRIPTION
**Pull request by flxbe**
jest and enzyme have been added to enable simple component and container
tests. In order to be able to test react components with async methods,
babel-preset-2015 was replaced with babel-preset-env.

The components are tested with snapshot-tests as well as more granular
shallow tests using enzyme. The containers are tested using enzyme shallow
tests.

The test can be invoked using "npm test".

This PR is a proposal for #10.

### CODE REVIEW

**Comment by alex-saunders** [comment]
@flxbe cheers for this, this is exactly what we were looking for. 
Would you be able to add some info about tests (framework choice, how they work, how to run tests etc.) in the readme as part of this PR?

**Comment by flxbe** [comment]
@alex-saunders I hope, this solves the issue. Let me know, if I can add anything.

**Comment by alex-saunders** [comment]
@flxbe looks great, thanks for this.

Merging now.

**Comment by flxbe** [comment]
Awesome! Thanks for fixing the typos :+1:

**Pull request merged**
