### PR TITLE
Split Scripts container's components 

### PR DESCRIPTION
**Pull request by CVarisco**
I'm working on the refactor of Scripts container splitting the render into small and testable components.

I put on WIP to warn you that I'm working on it 👍  and of course if you want to contribute 🙂 

Cheers 🍺

### CODE REVIEW

**Comment by alex-saunders** [comment]
Hi @CVarisco 

Sounds good! While I've been working on  #1 , I've been splitting up some of the scripts container as a byproduct of what I've been implementing. It might be best if you wait till I've merged my latest commit until you start working on this then (i'll probably be merging tomorrow).

**Comment by CVarisco** [comment]
Sure man!

Tell me when I can work on it after your merge ;)

**Comment by alex-saunders** [comment]
@CVarisco I've now merged my changes, you might have to alter some of your changes to get everything compatible but it shouldn't be too much 🙂

**Comment by CVarisco** [comment]
Hi @alex-saunders !

I divided into two different dumb components the Scripts container without touching anything on "business logic part".

But, I think that in the first future the application should be refactored because now the data flow inside the application seems a little bit tricky.
For example, we are using redux but not completely, why?
If you want we can improve a lot the code quality of the app and create a very solid application for the future improvements 🙂 

Tell me what do you think, I'm available to help you with this project in my free time because I think that is a good idea.

**Comment by alex-saunders** [comment]
I agree @CVarisco , my initial prototype was a very hacky and quickly thrown-together thing. I know that the data flow/management is not where I want it to be and I'd definitely be up for reviewing the data model and getting a full implementation of redux working.

Could you maybe create an issue detailing exactly what you think needs to be done for this refactor to enable a solid foundation for future development, and then we can have that conversation in a separate thread? Meanwhile, we'll keep this PR purely for splitting up the Scripts container into it's component parts so that this thread doesn't get too confusing.

**Comment by CVarisco** [comment]
Hi @alex-saunders !

The task should be complete.
When you are free check the last changes and tell me if for you is ok 🙂 

ps: Sorry for the delay, I'll create an issue for business logic improvements also.

**Comment by alex-saunders** [comment]
Hey @CVarisco ,

Really sorry about the delay on this, i've been incredibly busy IRL lately. I've not forgotten about this and will be reviewing your PR this week for sure.

Sorry again

**Comment by CVarisco** [comment]
Hi @alex-saunders,
don't worry man, the open source should be a pleasure, not a duty 😃

**Comment by alex-saunders** [comment]
Hi @CVarisco ,

This all looks good to me, merging now.

**Pull request merged**
