### PR TITLE
Integrate CSSModules

### PR DESCRIPTION
**Pull request by CVarisco**
What I did:

- Removed postcss (useless) 
- Added CSSModules
- Created variables partials
- Created theme (where you can find the override of the material component theme) scss file.
- Fixed the UI with CSSModules
- Added Extract-text-plugin to have a stylesheet file 

Referred to #5

### CODE REVIEW

**Comment by alex-saunders** [comment]
Cheers @CVarisco !

> Added Extract-text-plugin to have a stylesheet file

What's your reasoning for this? Not saying it's a bad idea, just interested to hear why you've done this.

**Comment by CVarisco** [comment]
Very happy to know that you like my contributions 🙂 

We have pros and const but basically, because we can split the bundle by type (and of course size).
In the future will be easier create different chunks for different reason (like vendor libs for example)

**Comment by alex-saunders** [comment]
Surely we can do this without having to place styles in stylesheets, with the usual css-loader?

That being said, if you're keen on using extract-text-plugin then i'm fine with it as it doesn't have any negative effects.

**Comment by CVarisco** [comment]
Yeah, I preferer that approach 🙂 
You have in both cases pros and const, and this decision is all about approach.

Feel free to choose whatever you want my friend 👍

**Comment by alex-saunders** [comment]
Sounds good, we'll go with extract-text-plugin then

Cheers again for getting css modules hooked up

**Pull request merged**
